---
parser: "@typescript-eslint/parser"
parserOptions:
    ecmaVersion: 2020
    sourceType: module
plugins:
    - unused-imports
extends:
    - "plugin:@typescript-eslint/recommended"
    - "prettier/@typescript-eslint"
    - "plugin:prettier/recommended"
    - "plugin:react/recommended"
rules:
    \@typescript-eslint/no-unused-vars: off
    unused-imports/no-unused-imports-ts: error
    unused-imports/no-unused-vars-ts: warn
    react/prop-types: off
    react/jsx-no-literals:
        - "error"
        - noStrings: false
          ignoreProps: true
          noAttributeStrings: false
